# Generated by Django 2.2.10 on 2020-02-29 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoitymoppet', '0002_userwishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('soulder_to_apex', models.CharField(max_length=255)),
                ('cap_sleeve_length', models.CharField(max_length=255)),
                ('short_sleeve_length', models.CharField(max_length=255)),
                ('three_fourth_to_apex', models.CharField(max_length=255)),
                ('full_sleeve_length', models.CharField(max_length=255)),
                ('knee_round', models.CharField(max_length=255)),
                ('calf', models.CharField(max_length=255)),
                ('ankle_round', models.CharField(max_length=255)),
                ('waist_length', models.CharField(max_length=255)),
                ('neck_round', models.CharField(max_length=255)),
                ('front_neck_depth', models.CharField(max_length=255)),
                ('cross_front', models.CharField(max_length=255)),
                ('bust', models.CharField(max_length=255)),
                ('under_bust', models.CharField(max_length=255)),
                ('waist', models.CharField(max_length=255)),
                ('lower_waist', models.CharField(max_length=255)),
                ('wrist', models.CharField(max_length=255)),
                ('thigh_round', models.CharField(max_length=255)),
                ('lower_thigh', models.CharField(max_length=255)),
                ('arm_hole', models.CharField(max_length=255)),
                ('knee_length', models.CharField(max_length=255)),
                ('full_length', models.CharField(max_length=255)),
                ('shoulder', models.CharField(max_length=255)),
                ('back_neck_depth', models.CharField(max_length=255)),
                ('biceps', models.CharField(max_length=255)),
                ('elbow_round', models.CharField(max_length=255)),
                ('hips', models.CharField(max_length=255)),
                ('bottom_length', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoitymoppet.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
