# Generated by Django 2.2.10 on 2020-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0003_usercustomsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.ManyToManyField(to='hoitymoppet.Age'),
        ),
    ]
