# Generated by Django 2.2.10 on 2020-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0004_auto_20200303_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
