# Generated by Django 2.2.10 on 2020-03-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0006_auto_20200303_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_size',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
