# Generated by Django 2.2.10 on 2020-03-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0008_auto_20200304_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustomsize',
            old_name='soulder_to_apex',
            new_name='shoulder_to_apex',
        ),
    ]
