# Generated by Django 2.2.10 on 2020-03-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0010_auto_20200304_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='parent_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcolor', to='hoitymoppet.Color'),
        ),
    ]
